CREATE PROC FI_SP_ConsBeneficiarios
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, IdCLiente, ID , CPF FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT NOME, IdCLiente, ID , CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
END